### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by IlyaMokin** [StYaroslav/Desktop-Telegram-UI#1]
Hello @StYaroslav, the Telegram looks quite good in general, please check the issues:
 - The main problem is top line. Your approach for scaling looks lie bad idea. It's what I see on my laptop
![image](https://user-images.githubusercontent.com/5592397/93760119-162fd380-fc14-11ea-92f1-e5cf1568d322.png)

 - also please check fonts. You can make the fonts closer to original

**Comment by StYaroslav** [comment]
Hello, Ilya, I've fixed these 2 problems and pushed them to my repo. Should
I send the form once again or not?

пн, 21 сент. 2020 г. в 14:10, Ilya Mokin <notifications@github.com>:

**Comment by ilya4321** [comment]
I see the same issue. That's a bad idea to scale the top line in that way (size in %)
![image](https://user-images.githubusercontent.com/5592397/93792683-80f60480-fc3e-11ea-9917-8d4705aaab1f.png)

**Comment by StYaroslav** [comment]
Hope everything is ok now :)

пн, 21 сент. 2020 г., 19:19 Ilya Mokin <notifications@github.com>:

**Comment by ilya4321** [comment]
Looks fine now, the task is accepted
